# Generated by Django 3.2.6 on 2021-09-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.CharField(max_length=150, verbose_name='Тезис')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Дебаты',
                'verbose_name_plural': 'Дебаты',
                'ordering': ['-id'],
            },
        ),
    ]
